import { toSrgb, parseColor } from "./color.mjs";
import { coupling, DEFAULT_THEME, derive, dimensions, profiles } from "./config.mjs";
import { readEngineCss, renderLibraryRecipesCss } from "./library-recipes.mjs";
import { derivePalette } from "./palette.mjs";
import { resolveFonts } from "./spec.mjs";
import { springEasing } from "./spring.mjs";
import { renderSpecCss } from "./theme-css.mjs";

const round = (value, places = 3) => Number(value.toFixed(places));

/**
 * The one spacing and type scale every recipe draws from. Theme-invariant on
 * purpose: theme varies radius, density of ink, motion and depth, while
 * the rhythm of the grid stays constant so composed pages line up. Recipes must
 * not invent values between these steps. Layers are the one stacking order
 * for everything that floats: raised content, sticky headers, menus, dialogs,
 * popovers, toasts and tooltips, and the few layers that sit above them all.
 */
export function renderScaleCss() {
  return `:root {
  --ml-space-px: 1px;
  --ml-space-0-5: 0.125rem;
  --ml-space-1: 0.25rem;
  --ml-space-1-5: 0.375rem;
  --ml-space-2: 0.5rem;
  --ml-space-2-5: 0.625rem;
  --ml-space-3: 0.75rem;
  --ml-space-3-5: 0.875rem;
  --ml-space-4: 1rem;
  --ml-space-4-5: 1.125rem;
  --ml-space-5: 1.25rem;
  --ml-space-6: 1.5rem;
  --ml-space-7: 1.75rem;
  --ml-space-8: 2rem;
  --ml-space-9: 2.25rem;
  --ml-space-10: 2.5rem;
  --ml-space-12: 3rem;
  --ml-space-14: 3.5rem;
  --ml-space-16: 4rem;
  --ml-type-2xs: 0.6875rem;
  --ml-type-xs: 0.75rem;
  --ml-type-sm: 0.8125rem;
  --ml-type-base: 0.875rem;
  --ml-type-md: 1rem;
  --ml-type-lg: 1.125rem;
  --ml-type-xl: 1.25rem;
  --ml-type-2xl: 1.5rem;
  --ml-leading-tight: 1.25;
  --ml-leading-snug: 1.4;
  --ml-leading-normal: 1.55;
  --ml-layer-raised: 10;
  --ml-layer-sticky: 20;
  --ml-layer-header: 30;
  --ml-layer-dropdown: 40;
  --ml-layer-overlay: 50;
  --ml-layer-modal: 51;
  --ml-layer-popover: 55;
  --ml-layer-toast: 60;
  --ml-layer-tooltip: 60;
  --ml-layer-top: 70;
}`;
}

/** Hex for the few browsers without OKLCH, derived from the default palette. */
function fallbackCss() {
  const palette = derivePalette(profiles[DEFAULT_THEME].spec, "light");
  const hex = (value) =>
    `#${toSrgb(parseColor(value)).map((channel) => Math.round(channel * 255).toString(16).padStart(2, "0")).join("")}`;
  const lines = Object.entries(palette).map(([token, value]) => `    --ml-${token}: ${hex(value)};`);
  return `@supports not (color: oklch(0 0 0)) {
  :root {
${lines.join("\n")}
  }
}`;
}

/**
 * Every canonical theme, rendered from its spec through the same function a
 * project theme or a Studio theme uses. The default theme also owns `:root`.
 */
export function renderTokensCss() {
  const themes = Object.entries(profiles).map(([id, profile]) =>
    renderSpecCss(profile.spec, { root: id === DEFAULT_THEME, aliases: profile.aliases, banner: false }),
  );
  return `/* Generated by @mlola-ui/engine from the canonical theme specs. Do not hand edit. */
${renderScaleCss()}

${themes.join("\n")}
${fallbackCss()}`;
}

export function renderFoundationsCss() {
  return `/* Foundation layer. */\n${readEngineCss("foundations")}`;
}

export function renderMaterialsCss() {
  return `/* Material recipes: apply a material to one surface regardless of theme. */\n${readEngineCss("materials")}`;
}

export function renderRecipesCss() {
  return renderLibraryRecipesCss();
}

export function renderMotionCss() {
  return `/* Motion and accessibility layer. */\n${readEngineCss("motion")}`;
}

export function renderAccessibilityCss() {
  return `/* Accessibility layer: last in the cascade, so these guarantees hold over any recipe. */\n${readEngineCss("accessibility")}`;
}

export function renderDtcg() {
  const dtcgColor = (value) => {
    const match = value.match(/^oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)(?:\s*\/\s*([\d.]+))?\)$/);
    if (!match) return value;
    return {
      colorSpace: "oklch",
      components: match.slice(1, 4).map(Number),
      alpha: match[4] === undefined ? 1 : Number(match[4]),
    };
  };
  const output = {
    $schema: "https://tr.designtokens.org/format/",
    $description: "Generated Mlola UI theme tokens. Values use the DTCG 2025.10 format.",
    theme: {
      $description: "Theme vector dimensions normalized to [0,1].",
      dimensions: Object.fromEntries(dimensions.map(([name, low, high], index) => [
        name,
        {
          $type: "number",
          $value: index,
          $description: `${low} (0) → ${high} (1)`,
          $extensions: { "com.mlola.axis": { low, high } },
        },
      ])),
      coupling: Object.fromEntries(Object.entries(coupling).map(([name, value]) => [name, { $type: "number", $value: value }])),
    },
    profile: {},
  };

  for (const [name, profile] of Object.entries(profiles)) {
    const derived = derive(profile);
    const fonts = resolveFonts(profile.spec.fonts);
    output.profile[name] = {
      $description: `${profile.label} theme profile, derived from its spec.`,
      $extensions: { "com.mlola.spec": profile.spec },
      vector: {
        $description: "Ordered τ vector is available in the com.mlola.vector extension.",
        $extensions: { "com.mlola.vector": profile.vector },
        ...Object.fromEntries(dimensions.map(([dimension], index) => [dimension, { $type: "number", $value: profile.vector[index] }])),
      },
      light: Object.fromEntries(Object.entries(derivePalette(profile.spec, "light")).map(([token, value]) => [token, { $type: "color", $value: dtcgColor(value) }])),
      dark: Object.fromEntries(Object.entries(derivePalette(profile.spec, "dark")).map(([token, value]) => [token, { $type: "color", $value: dtcgColor(value) }])),
      geometry: {
        radius: { $type: "dimension", $value: { value: round(derived.radius), unit: "px" } },
        border: { $type: "dimension", $value: { value: derived.border >= 1.4 ? 1.5 : 1, unit: "px" } },
        control: { $type: "dimension", $value: { value: round(derived.controlHeight, 4), unit: "rem" } },
        targetMin: { $type: "dimension", $value: { value: 44, unit: "px" } },
      },
      motion: {
        fast: { $type: "duration", $value: { value: Math.round(derived.durationFast), unit: "ms" } },
        normal: { $type: "duration", $value: { value: Math.round(derived.durationNormal), unit: "ms" } },
        slow: { $type: "duration", $value: { value: Math.round(derived.durationSlow), unit: "ms" } },
        reveal: { $type: "duration", $value: { value: Math.round(derived.durationReveal), unit: "ms" } },
        easing: { $type: "cubicBezier", $value: [0.2, 0, 0, 1] },
        $extensions: {
          "com.mlola.spring": {
            omega: round(derived.springOmega, 3),
            damping: round(derived.springDamping, 3),
            bounceDamping: round(derived.springBounceDamping, 3),
            spring: springEasing({ omega: derived.springOmega, damping: derived.springDamping }),
            bounce: springEasing(
              { omega: derived.springOmega, damping: derived.springBounceDamping },
              28,
            ),
          },
        },
      },
      typography: {
        body: {
          $type: "typography",
          $value: {
            fontFamily: (fonts.sans.match(/"([^"]+)"/)?.[1] ?? fonts.sans.split(",")[0]).trim(),
            fontSize: { value: 16, unit: "px" },
            fontWeight: 400,
            letterSpacing: { value: round(derived.tracking, 4), unit: "em" },
            lineHeight: round(derived.bodyLeading),
          },
        },
      },
    };
  }
  return output;
}
