import { derive } from "./config.mjs";
import { darkShadowDeclarations, PALETTE_DERIVED, themeDeclarations } from "./declarations.mjs";
import { derivePalette } from "./palette.mjs";
import { springEasing } from "./spring.mjs";

/**
 * The one way a theme becomes CSS.
 *
 * Canonical themes, `mlola.theme.json`, and themes generated in the Studio all
 * render through this function, in Node at build time or in the browser for a
 * live preview. It has no dependencies beyond the engine's own pure modules.
 */

const indent = (lines) => lines.map((line) => `  ${line};`).join("\n");

function paletteLines(palette) {
  return Object.entries(palette).map(([token, value]) => `--ml-${token}: ${value}`);
}

/** The theme's selectors, for light (no mode), or for a mode: "dark", or "system" (dark only when the reader asks for it). */
function selectorList(spec, { root, aliases }, mode) {
  const attributes = [spec.id, ...aliases].map((name) => `[data-theme="${name}"]`);
  const list = [];
  if (root) list.push(":root");
  for (const attribute of attributes) list.push(`:root${attribute}`, attribute);
  if (!mode) return list.join(",\n");
  return list.map((selector) => `${selector}[data-mode="${mode}"]`).join(",\n");
}

/**
 * Render a normalized spec as a self-contained stylesheet.
 *
 * `root` also applies the theme to `:root`, which only the default theme
 * does. `aliases` are further `data-theme` names for the same theme, such as
 * the readable name a Studio theme carries beside its unique id.
 *
 * @param {any} spec
 * @param {{ root?: boolean, aliases?: string[], banner?: boolean }} [options]
 */
export function renderSpecCss(spec, { root = false, aliases = [], banner = true } = {}) {
  const derived = derive(spec);
  const light = derivePalette(spec, "light");
  const dark = derivePalette(spec, "dark");
  const easing = springEasing({ omega: derived.springOmega, damping: derived.springDamping });
  const bounce = springEasing({ omega: derived.springOmega, damping: derived.springBounceDamping }, 28);
  const options = { root, aliases };

  const title = spec.label.replace(/\*\//g, "* /");
  const darkBlock = `  color-scheme: dark;\n${indent(paletteLines(dark))}\n${indent(darkShadowDeclarations(spec.vector))}\n${indent(PALETTE_DERIVED)}`;
  return `${banner ? `/* ${title} — generated by @mlola-ui/engine from its theme spec. Do not hand edit. */\n` : ""}${selectorList(spec, options, false)} {
  color-scheme: light;
${indent(themeDeclarations(spec))}
${indent(paletteLines(light))}
${indent(PALETTE_DERIVED)}
}

${selectorList(spec, options, "dark")} {
${darkBlock}
}

/* data-mode="system" follows the reader's setting: light by default, dark when they ask for it. */
@media (prefers-color-scheme: dark) {
${selectorList(spec, options, "system")} {
${darkBlock}
}
}

@supports (transition-timing-function: linear(0, 1)) {
${selectorList(spec, options, false)} {
  --ml-ease-spring: ${easing};
  --ml-ease-bounce: ${bounce};
}
}
`;
}
