import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import {
  DEFAULT_CONFIG,
  loadConfig,
  targetRoot,
  writeDefaultConfig,
} from "./config.js";
import { writeAgentFiles } from "./agents.js";
import { addAssets, assetHint, loadAssetIndex } from "./assets.js";
import { runDoctor } from "./doctor.js";
import { collectEngineDependencies, installItems } from "./installer.js";
import { loadCatalogNames, loadRegistry, resolveItems } from "./registry.js";
import { clearCredentials, fetchProItems, GUIDE_FILENAME, hostFrom, readCredentials, saveCredentials, verifyToken, writeProGuide, writeProStyles } from "./pro.js";
import { serveMcp } from "./mcp.js";
import { pullTheme } from "./theme-pull.js";

const HELP = `Mlola UI — source-copy components with Theme

Usage:
  mlola-ui init [--force] [--no-agents]
  mlola-ui agents
  mlola-ui mcp
  mlola-ui add <name...> [--overwrite] [--install|--yes]
  mlola-ui add asset <id...> [--overwrite]
  mlola-ui login <token> [--host <url>]
  mlola-ui logout
  mlola-ui list [--kind component|block|template|asset] [--json]
  mlola-ui doctor
  mlola-ui theme pull <theme-id | url> [--host <url>] [--overwrite]

Examples:
  npx mlola-ui init                   (also tells your coding agents about Mlola)
  npx mlola-ui add button card
  npx mlola-ui login mlp_…          (Mlola Pro: a token from /account)
  npx mlola-ui add conversation bot
  npx mlola-ui add asset empty-inbox orb
  npx mlola-ui list --kind block
  npx mlola-ui theme pull https://ui.mlola.com/t/th-4k2x9qf7wz3m
  npx mlola-ui mcp                    (an MCP server for Claude Code, Cursor, Codex…)
`;

const CLI_VERSION = JSON.parse(fs.readFileSync(new URL("../package.json", import.meta.url), "utf8")).version;

function reportAgents(results, output) {
  const changed = results.filter((entry) => entry.status !== "unchanged");
  for (const { file, status } of changed) output.log(`✓ ${status[0].toUpperCase()}${status.slice(1)} ${file}`);
  if (!changed.length) output.log("• Agent instructions are up to date");
  output.log("Coding agents now know this UI is Mlola: AGENTS.md points them at mlola.agents.md, and .mcp.json starts the Mlola MCP server.");
}

function hasFlag(args, ...names) {
  return args.some((argument) => names.includes(argument));
}

function optionValue(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
}

function writeStyles(cwd, config, force) {
  const relative = path.join(targetRoot(config, "styles"), "mlola", "index.css");
  const filename = path.join(cwd, relative);
  if (fs.existsSync(filename) && !force) return { relative, created: false };
  fs.mkdirSync(path.dirname(filename), { recursive: true });
  fs.writeFileSync(
    filename,
    `/* Generated by mlola-ui init. Import this file once in your app. */\n@import "${config.engine.engine ?? "@mlola-ui/engine"}";\n`,
  );
  return { relative, created: true };
}

function packageManager(cwd) {
  if (fs.existsSync(path.join(cwd, "pnpm-lock.yaml"))) return ["pnpm", ["add"]];
  if (fs.existsSync(path.join(cwd, "yarn.lock"))) return ["yarn", ["add"]];
  if (fs.existsSync(path.join(cwd, "bun.lockb")) || fs.existsSync(path.join(cwd, "bun.lock"))) {
    return ["bun", ["add"]];
  }
  return ["npm", ["install"]];
}

function installEngines(cwd, dependencies, output) {
  if (!dependencies.size) return 0;
  const [command, baseArgs] = packageManager(cwd);
  const packages = [...dependencies].map(([name, range]) => `${name}@${range}`);
  output.log(`Installing ${packages.join(", ")}...`);
  const result = spawnSync(command, [...baseArgs, ...packages], { cwd, stdio: "inherit" });
  if (result.error) {
    output.error(`Unable to run ${command}: ${result.error.message}`);
    return 1;
  }
  return result.status ?? 1;
}

export async function run(argv, options = {}) {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const output = options.output ?? console;
  const env = options.env ?? process.env;
  const fetcher = options.fetch ?? fetch;
  const [command = "help", ...args] = argv;

  try {
    if (command === "help" || command === "--help" || command === "-h") {
      output.log(HELP);
      return 0;
    }

    if (command === "init") {
      const force = hasFlag(args, "--force");
      const configResult = writeDefaultConfig(cwd, { force });
      const config = configResult.created ? DEFAULT_CONFIG : loadConfig(cwd);
      const stylesResult = writeStyles(cwd, config, force);
      output.log(
        configResult.created
          ? `✓ Created ${path.relative(cwd, configResult.filename)}`
          : `• Kept existing ${path.relative(cwd, configResult.filename)}`,
      );
      output.log(
        stylesResult.created
          ? `✓ Created ${stylesResult.relative}`
          : `• Kept existing ${stylesResult.relative}`,
      );
      output.log(
        `Set data-theme="${config.theme}" on your document root and import ${stylesResult.relative}.`,
      );
      output.log(
        `Install the engines you use, starting with: npm install ${config.engine.engine ?? "@mlola-ui/engine"} ${config.engine.motion}`,
      );
      if (!hasFlag(args, "--no-agents")) reportAgents(writeAgentFiles(cwd), output);
      return 0;
    }

    if (command === "agents") {
      reportAgents(writeAgentFiles(cwd), output);
      return 0;
    }

    if (command === "mcp") {
      await serveMcp({ cwd, run, version: CLI_VERSION });
      return 0;
    }

    if (command === "list") {
      const registry = loadRegistry();
      const kind = optionValue(args, "--kind");
      if (kind && !["component", "block", "template", "asset"].includes(kind)) {
        throw new Error(`--kind must be component, block, template or asset (received "${kind}")`);
      }
      if (kind === "asset") {
        const assets = loadAssetIndex().items;
        if (hasFlag(args, "--json")) {
          output.log(JSON.stringify(assets, null, 2));
          return 0;
        }
        for (const group of ["2d", "3d"]) {
          const grouped = assets.filter((item) => item.kind === group);
          if (!grouped.length) continue;
          output.log(`${group === "2d" ? "Illustrations" : "3D models"} (${grouped.length})`);
          for (const item of grouped) output.log(`  ${item.id.padEnd(18)} ${item.summary}`);
        }
        return 0;
      }
      const items = kind
        ? registry.items.filter((item) => item.type === {
            component: "registry:ui",
            block: "registry:block",
            template: "registry:page",
          }[kind])
        : registry.items;
      if (hasFlag(args, "--json")) {
        output.log(JSON.stringify(items, null, 2));
      } else {
        for (const group of ["registry:ui", "registry:block", "registry:page"]) {
          const grouped = items.filter((item) => item.type === group);
          if (!grouped.length) continue;
          const label = {
            "registry:ui": "Components",
            "registry:block": "Blocks",
            "registry:page": "Templates",
          }[group];
          output.log(`${label} (${grouped.length})`);
          for (const item of grouped) output.log(`  ${item.name.padEnd(18)} ${item.description}`);
        }
      }
      return 0;
    }

    if (command === "login") {
      const token = args.find((argument) => !argument.startsWith("-") && argument !== optionValue(args, "--host"));
      const host = hostFrom(env, optionValue(args, "--host"));
      if (!token) throw new Error(`Usage: mlola-ui login <token>. Create a token at ${host}/account.`);
      const { licence } = await verifyToken(host, token, fetcher);
      const filename = saveCredentials(env, token, host === hostFrom(env) ? undefined : host);
      output.log(`✓ Logged in to Mlola Pro (${licence.plan} license). Token saved to ${filename}.`);
      return 0;
    }

    if (command === "logout") {
      output.log(clearCredentials(env) ? "✓ Logged out of Mlola Pro." : "• Not logged in.");
      return 0;
    }

    if (command === "add" && args[0] === "asset") {
      const host = optionValue(args, "--host");
      const ids = args.slice(1).filter((argument) => !argument.startsWith("-") && argument !== host);
      if (!ids.length) throw new Error('Usage: mlola-ui add asset <id...>. See them with "npx mlola-ui list --kind asset".');
      const config = loadConfig(cwd);
      const source = env.MLOLA_ASSETS_URL?.replace(/\/$/, "") ?? `${hostFrom(env, host)}/asset-files`;
      const result = await addAssets(cwd, config, ids, { source, fetcher, overwrite: hasFlag(args, "--overwrite") });
      for (const filename of result.written) output.log(`✓ Added ${filename}`);
      if (result.unchanged.length) output.log(`• ${result.unchanged.length} file(s) already up to date`);
      if (result.conflicts.length) {
        output.error(`✗ Refused to replace ${result.conflicts.length} modified file(s):\n  ${result.conflicts.join("\n  ")}\nRun again with --overwrite to replace them.`);
        return 1;
      }
      for (const item of result.items) output.log(assetHint(config, item));
      return 0;
    }

    if (command === "add") {
      const names = args.filter((argument) => !argument.startsWith("-"));
      if (!names.length) throw new Error("Usage: mlola-ui add <name...>");
      const overwrite = hasFlag(args, "--overwrite");
      const bundled = loadRegistry();
      const config = loadConfig(cwd);
      const catalogNames = loadCatalogNames();
      const proNames = names.filter((name) => catalogNames.has(name));

      // Pro items come from the service with their Pro dependencies; free ones from the bundle.
      let registry = bundled;
      let styles = [];
      let guide = null;
      if (proNames.length) {
        const credentials = readCredentials(env);
        const host = hostFrom(env, credentials?.host);
        if (!credentials) {
          throw new Error(
            `${proNames.map((name) => `"${name}"`).join(", ")} ${proNames.length === 1 ? "is" : "are"} part of Mlola Pro. ` +
              `With a license, create a token at ${host}/account and run "npx mlola-ui login <token>". See ${host}/pricing to get Pro.`,
          );
        }
        const delivered = await fetchProItems(host, credentials.token, proNames, fetcher);
        const known = new Set(bundled.items.map((item) => item.name));
        registry = { ...bundled, items: [...bundled.items, ...delivered.items.filter((item) => !known.has(item.name))] };
        styles = delivered.styles;
        guide = delivered.guide;
      }

      const items = resolveItems(registry, names, catalogNames);
      const result = installItems(cwd, registry, items, config, { overwrite });
      const styleResult = writeProStyles(cwd, config, styles, { overwrite });
      result.written.push(...styleResult.written);
      result.unchanged.push(...styleResult.unchanged);
      result.conflicts.push(...styleResult.conflicts);
      const guideResult = writeProGuide(cwd, guide, { overwrite });
      if (guideResult.status === "written") result.written.push(GUIDE_FILENAME);
      if (guideResult.status === "unchanged") result.unchanged.push(GUIDE_FILENAME);
      if (guideResult.status === "conflict") result.conflicts.push(GUIDE_FILENAME);
      for (const filename of result.written) output.log(`✓ Added ${filename}`);
      if (result.unchanged.length) {
        output.log(`• ${result.unchanged.length} file(s) already match the registry`);
      }
      if (result.conflicts.length) {
        output.error(
          `✗ Refused to replace ${result.conflicts.length} modified file(s):\n  ${result.conflicts.join(
            "\n  ",
          )}\nRun again with --overwrite to replace them.`,
        );
        return 1;
      }

      if (styleResult.index) output.log(`Pro styles are gathered in ${styleResult.index}; import it once, after the engine stylesheet.`);
      if (guideResult.status === "written") output.log(`Coding agents: point your AGENTS.md at ${GUIDE_FILENAME}, which lists every Pro class and attribute.`);

      const engines = collectEngineDependencies(items);
      if (engines.size && hasFlag(args, "--install", "--yes")) {
        return installEngines(cwd, engines, output);
      }
      if (engines.size) {
        output.log(
          `Engine dependencies: ${[...engines]
            .map(([name, range]) => `${name}@${range}`)
            .join(" ")}`,
        );
      }
      return 0;
    }

    if (command === "theme") {
      const [subcommand, reference] = args;
      if (subcommand !== "pull") throw new Error(`Unknown theme command "${subcommand ?? ""}". Try: mlola-ui theme pull <theme-id | url>`);
      await pullTheme(cwd, reference, {
        host: optionValue(args, "--host") ?? (process.env.MLOLA_STUDIO_URL || undefined),
        overwrite: hasFlag(args, "--overwrite"),
        fetcher,
        output,
      });
      return 0;
    }

    if (command === "doctor") {
      const findings = runDoctor(cwd);
      for (const item of findings) {
        const symbol = item.level === "pass" ? "✓" : item.level === "warn" ? "!" : "✗";
        const writer = item.level === "error" ? output.error : output.log;
        writer.call(output, `${symbol} ${item.message}`);
      }
      const errors = findings.filter((item) => item.level === "error").length;
      const warnings = findings.filter((item) => item.level === "warn").length;
      output.log(`Doctor completed with ${errors} error(s) and ${warnings} warning(s).`);
      return errors ? 1 : 0;
    }

    output.error(`Unknown command "${command}".\n\n${HELP}`);
    return 1;
  } catch (error) {
    output.error(`✗ ${error.message}`);
    return 1;
  }
}
