import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { profiles } from "./src/config.mjs";
import { renderContract, renderProContract } from "./src/contract.mjs";
import { renderCatalogCss } from "./src/library-recipes.mjs";
import { renderSpecSchema } from "./src/spec.mjs";
import { renderThemeCss, renderThemeManifest } from "./src/theme.mjs";
import {
  renderAccessibilityCss,
  renderDtcg,
  renderFoundationsCss,
  renderMaterialsCss,
  renderMotionCss,
  renderRecipesCss,
  renderTokensCss,
} from "./src/render.mjs";

const engineDirectory = dirname(fileURLToPath(import.meta.url));
const packagesDirectory = dirname(engineDirectory);
const repositoryDirectory = dirname(packagesDirectory);
const generatedDirectory = join(engineDirectory, "generated");
const tokenGeneratedDirectory = join(packagesDirectory, "tokens", "generated");
const check = process.argv.includes("--check");

const layers = {
  "tokens.css": renderTokensCss(),
  "foundations.css": renderFoundationsCss(),
  "materials.css": renderMaterialsCss(),
  "recipes.css": renderRecipesCss(),
  "motion.css": renderMotionCss(),
  "accessibility.css": renderAccessibilityCss(),
};

const layerOrder = "mlola.tokens, mlola.foundations, mlola.materials, mlola.recipes, mlola.motion, mlola.accessibility";
const aggregate = `/* Generated by @mlola-ui/engine. React and Tailwind are not required. */
@layer ${layerOrder};
@import "./tokens.css" layer(mlola.tokens);
/* The project theme is a token source too, imported last within the same
   layer so a brand wins over every canonical theme. */
@import "./theme.css" layer(mlola.tokens);
@import "./foundations.css" layer(mlola.foundations);
@import "./materials.css" layer(mlola.materials);
@import "./recipes.css" layer(mlola.recipes);
@import "./motion.css" layer(mlola.motion);
@import "./accessibility.css" layer(mlola.accessibility);
`;

const dtcg = `${JSON.stringify(renderDtcg(), null, 2)}\n`;
const manifest = `${JSON.stringify({
  generatedAt: "deterministic",
  generator: "@mlola-ui/engine",
  profileCount: Object.keys(profiles).length,
}, null, 2)}\n`;

const outputs = new Map();
for (const [name, contents] of Object.entries(layers)) {
  outputs.set(join(generatedDirectory, name), `${contents.trim()}\n`);
  outputs.set(join(tokenGeneratedDirectory, name), `${contents.trim()}\n`);
}
outputs.set(join(generatedDirectory, "mlola.css"), aggregate);
outputs.set(join(tokenGeneratedDirectory, "mlola.css"), aggregate);
// A project theme is optional. When present it is compiled alongside the
// canonical themes and selects on the same data-theme contract.
const themeFile = join(repositoryDirectory, "mlola.theme.json");
let projectTheme = "";
try {
  projectTheme = renderThemeCss(JSON.parse(await readFile(themeFile, "utf8")));
} catch (error) {
  if (error?.code !== "ENOENT") {
    throw new Error(`mlola.theme.json is present but unusable: ${error.message}`);
  }
}
outputs.set(join(generatedDirectory, "theme.css"), projectTheme || "/* No mlola.theme.json in this project. */\n");

const themeManifest = `${JSON.stringify(
  {
    version: 1,
    description:
      "Themes compiled into this build. A project theme from mlola.theme.json appears here alongside the canonical ones.",
    themes: renderThemeManifest(
      projectTheme ? JSON.parse(await readFile(themeFile, "utf8")) : null,
    ),
  },
  null,
  2,
)}\n`;
outputs.set(join(generatedDirectory, "themes.json"), themeManifest);

// The spec schema is what editors, the CLI, and models validate a theme against.
outputs.set(join(generatedDirectory, "theme-spec.schema.json"), `${JSON.stringify(renderSpecSchema(), null, 2)}\n`);

// The commercial catalog's styles are assembled here but written outside the
// engine package, so publishing the engine can never ship them.
outputs.set(join(packagesDirectory, "registry", "catalog", "generated", "catalog.css"), renderCatalogCss());

const contract = `${JSON.stringify(renderContract(), null, 2)}\n`;
outputs.set(join(generatedDirectory, "contract.json"), contract);
// Pro's half of the contract stays beside the Pro catalog, out of the published engine.
outputs.set(join(packagesDirectory, "registry", "catalog", "generated", "contract.json"), `${JSON.stringify(renderProContract(), null, 2)}\n`);
outputs.set(join(generatedDirectory, "tokens.json"), dtcg);
outputs.set(join(packagesDirectory, "tokens", "tokens.json"), dtcg);
outputs.set(join(generatedDirectory, "manifest.json"), manifest);

const changed = [];
for (const [path, contents] of outputs) {
  let previous = null;
  try {
    previous = await readFile(path, "utf8");
  } catch {
    // Missing output is a change.
  }
  if (previous === contents) continue;
  changed.push(path.replace(`${repositoryDirectory}/`, ""));
  if (!check) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents);
  }
}

if (check && changed.length) {
  console.error(`Generated output is stale:\n${changed.map((path) => `- ${path}`).join("\n")}`);
  process.exitCode = 1;
} else {
  console.log(check ? "Generated output is current." : `Generated ${outputs.size} files.`);
}
