/* Generated by npm run assets:2d. Every 2D asset as a React component, by id. */
import { EmptyInboxIllustration } from "./empty-inbox/empty-inbox";
import { NoResultsIllustration } from "./no-results/no-results";
import { EmptyCartIllustration } from "./empty-cart/empty-cart";
import { UploadIllustration } from "./upload/upload";
import { OfflineIllustration } from "./offline/offline";
import { NotFoundIllustration } from "./not-found/not-found";
import { SuccessIllustration } from "./success/success";
import { EmptyCalendarIllustration } from "./empty-calendar/empty-calendar";
import { SecureIllustration } from "./secure/secure";
import { EmptyFolderIllustration } from "./empty-folder/empty-folder";
import { ChatEmptyIllustration } from "./chat-empty/chat-empty";
import { IntegrationsIllustration } from "./integrations/integrations";
import { AnalyticsIllustration } from "./analytics/analytics";
import { ArchiveIllustration } from "./archive/archive";
import { BlueprintIllustration } from "./blueprint/blueprint";
import { BookmarksIllustration } from "./bookmarks/bookmarks";
import { ChecklistIllustration } from "./checklist/checklist";
import { CloudSyncIllustration } from "./cloud-sync/cloud-sync";
import { DataVaultIllustration } from "./data-vault/data-vault";
import { DashboardIllustration } from "./dashboard/dashboard";
import { DownloadIllustration } from "./download/download";
import { DocumentsIllustration } from "./documents/documents";
import { FiltersIllustration } from "./filters/filters";
import { InventoryIllustration } from "./inventory/inventory";
import { LinkIllustration } from "./link/link";
import { MaintenanceIllustration } from "./maintenance/maintenance";
import { ModulesIllustration } from "./modules/modules";
import { NotificationsIllustration } from "./notifications/notifications";
import { PackageTrackingIllustration } from "./package-tracking/package-tracking";
import { RoadmapIllustration } from "./roadmap/roadmap";
import { SearchIndexIllustration } from "./search-index/search-index";
import { SettingsIllustration } from "./settings/settings";
import { StorageIllustration } from "./storage/storage";
import { TerminalIllustration } from "./terminal/terminal";
import { TimeIllustration } from "./time/time";
import { WorkflowIllustration } from "./workflow/workflow";

export const ILLUSTRATIONS = {
  "empty-inbox": EmptyInboxIllustration,
  "no-results": NoResultsIllustration,
  "empty-cart": EmptyCartIllustration,
  "upload": UploadIllustration,
  "offline": OfflineIllustration,
  "not-found": NotFoundIllustration,
  "success": SuccessIllustration,
  "empty-calendar": EmptyCalendarIllustration,
  "secure": SecureIllustration,
  "empty-folder": EmptyFolderIllustration,
  "chat-empty": ChatEmptyIllustration,
  "integrations": IntegrationsIllustration,
  "analytics": AnalyticsIllustration,
  "archive": ArchiveIllustration,
  "blueprint": BlueprintIllustration,
  "bookmarks": BookmarksIllustration,
  "checklist": ChecklistIllustration,
  "cloud-sync": CloudSyncIllustration,
  "data-vault": DataVaultIllustration,
  "dashboard": DashboardIllustration,
  "download": DownloadIllustration,
  "documents": DocumentsIllustration,
  "filters": FiltersIllustration,
  "inventory": InventoryIllustration,
  "link": LinkIllustration,
  "maintenance": MaintenanceIllustration,
  "modules": ModulesIllustration,
  "notifications": NotificationsIllustration,
  "package-tracking": PackageTrackingIllustration,
  "roadmap": RoadmapIllustration,
  "search-index": SearchIndexIllustration,
  "settings": SettingsIllustration,
  "storage": StorageIllustration,
  "terminal": TerminalIllustration,
  "time": TimeIllustration,
  "workflow": WorkflowIllustration,
} as const;
