/* Generated by npm run assets:2d. Every 2D asset as a React component, by id. */
import { EmptyInboxIllustration } from "./empty-inbox/empty-inbox";
import { NoResultsIllustration } from "./no-results/no-results";
import { EmptyCartIllustration } from "./empty-cart/empty-cart";
import { UploadIllustration } from "./upload/upload";
import { OfflineIllustration } from "./offline/offline";
import { NotFoundIllustration } from "./not-found/not-found";
import { SuccessIllustration } from "./success/success";
import { EmptyCalendarIllustration } from "./empty-calendar/empty-calendar";
import { SecureIllustration } from "./secure/secure";
import { EmptyFolderIllustration } from "./empty-folder/empty-folder";
import { ChatEmptyIllustration } from "./chat-empty/chat-empty";
import { IntegrationsIllustration } from "./integrations/integrations";

export const ILLUSTRATIONS = {
  "empty-inbox": EmptyInboxIllustration,
  "no-results": NoResultsIllustration,
  "empty-cart": EmptyCartIllustration,
  "upload": UploadIllustration,
  "offline": OfflineIllustration,
  "not-found": NotFoundIllustration,
  "success": SuccessIllustration,
  "empty-calendar": EmptyCalendarIllustration,
  "secure": SecureIllustration,
  "empty-folder": EmptyFolderIllustration,
  "chat-empty": ChatEmptyIllustration,
  "integrations": IntegrationsIllustration,
} as const;
